# Generated by Django 2.2.5 on 2019-10-27 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('idcarrera', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('idcarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('iddocente', models.IntegerField(primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=25)),
                ('snombre', models.CharField(max_length=25)),
                ('pApellido', models.CharField(max_length=25)),
                ('sApellido', models.CharField(max_length=25)),
                ('fNacimiento', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idestudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('pnombre', models.CharField(max_length=25)),
                ('snombre', models.CharField(max_length=25)),
                ('pApellido', models.CharField(max_length=25)),
                ('sApellido', models.CharField(max_length=25)),
                ('fNacimiento', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=25)),
                ('idcarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.Carrera')),
                ('iddocente', models.ManyToManyField(to='App2.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='grado',
            fields=[
                ('idgrado', models.IntegerField(primary_key=True, serialize=False)),
                ('grado', models.IntegerField()),
                ('seccion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('idcarrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.Carrera')),
                ('idcurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.Curso')),
                ('iddocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.Docente')),
                ('idestudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.Estudiante')),
                ('idgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.grado')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='idgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.grado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='iddocente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.Docente'),
        ),
        migrations.AddField(
            model_name='curso',
            name='idgrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App2.grado'),
        ),
    ]
